name: MAZO
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ^3.7.2
dependencies:
  better_player_plus: ^1.0.8
  cached_network_image: ^3.4.1
  connectivity_plus: ^6.1.4
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter:
    sdk: flutter
  flutter_spinkit: ^5.2.1
  flutter_staggered_grid_view: ^0.7.0
  go_router: ^15.1.2
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  image_picker: ^1.1.2
  permission_handler: ^12.0.0+1
  pinput: ^5.0.1
  provider: ^6.1.5
  shared_preferences: ^2.5.3
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/img/
